const krCapitals = {
    "Kabul": "카불",
    "Tirana": "티라나",
    "Algiers": "알제",
    "Andorra la Vella": "안도라라벨랴",
    "Luanda": "루안다",
    "Saint John's": "세인트존스",
    "Buenos Aires": "부에노스아이레스",
    "Yerevan": "예레반",
    "Canberra": "캔버라",
    "Vienna": "빈",
    "Baku": "바쿠",
    "Nassau": "나소",
    "Manama": "마나마",
    "Dhaka": "다카",
    "Bridgetown": "브리지타운",
    "Minsk": "민스크",
    "Brussels": "브뤼셀",
    "Belmopan": "벨모판",
    "Porto-Novo": "포르토노보",
    "The Valley": "더밸리",
    "Mariehamn": "마리에함",
    "Pago Pago": "파고파고",
    "Port-aux-Français": "포르토프랑세",
    "Gustavia": "구스타비아",
    "Jamestown": "제임스타운",
    "Thimphu": "팀부",
    "Sucre": "수크레",
    "Sarajevo": "사라예보",
    "Gaborone": "가보로네",
    "Brasília": "브라질리아",
    "West Island": "웨스트아일랜드",
    "Bandar Seri Begawan": "반다르스리브가완",
    "Sofia": "소피아",
    "Ouagadougou": "와가두구",
    "Gitega": "기테가",
    "Praia": "프라이아",
    "Phnom Penh": "프놈펜",
    "Yaoundé": "야운데",
    "Ottawa": "오타와",
    "Bangui": "방기",
    "N'Djamena": "은자메나",
    "Santiago": "산티아고",
    "Beijing": "베이징",
    "Bogotá": "보고타",
    "Moroni": "모로니",
    "Kinshasa": "킨샤사",
    "Brazzaville": "브라자빌",
    "San José": "산호세",
    "Yamoussoukro": "야무수크로",
    "Zagreb": "자그레브",
    "Havana": "아바나",
    "Nicosia": "니코시아",
    "Prague": "프라하",
    "Copenhagen": "코펜하겐",
    "Djibouti": "지부티",
    "Roseau": "로조",
    "Santo Domingo": "산토도밍고",
    "Dili": "딜리",
    "Quito": "키토",
    "Cairo": "카이로",
    "San Salvador": "산살바도르",
    "Malabo": "말라보",
    "Asmara": "아스마라",
    "Tallinn": "탈린",
    "Mbabane": "음바바네",
    "Addis Ababa": "아디스아바바",
    "Palikir": "팔리키르",
    "Suva": "수바",
    "Helsinki": "헬싱키",
    "Paris": "파리",
    "Libreville": "리브르빌",
    "Banjul": "반줄",
    "Tbilisi": "트빌리시",
    "Berlin": "베를린",
    "Accra": "아크라",
    "Athens": "아테네",
    "St. George's": "세인트조지스",
    "Guatemala City": "과테말라시티",
    "Conakry": "코나크리",
    "Bissau": "비사우",
    "Georgetown": "조지타운",
    "Port-au-Prince": "포르토프랭스",
    "Tegucigalpa": "테구시갈파",
    "Budapest": "부다페스트",
    "Reykjavik": "레이캬비크",
    "New Delhi": "뉴델리",
    "Jakarta": "자카르타",
    "Tehran": "테헤란",
    "Baghdad": "바그다드",
    "Dublin": "더블린",
    "Jerusalem": "예루살렘",
    "Rome": "로마",
    "Kingston": "킹스턴",
    "Tokyo": "도쿄",
    "Amman": "암만",
    "Astana": "아스타나",
    "Nairobi": "나이로비",
    "Tarawa": "타라와",
    "Pyongyang": "평양",
    "Seoul": "서울",
    "Pristina": "프리슈티나",
    "Kuwait City": "쿠웨이트시티",
    "Bishkek": "비슈케크",
    "Vientiane": "비엔티안",
    "Riga": "리가",
    "Beirut": "베이루트",
    "Maseru": "마세루",
    "Monrovia": "몬로비아",
    "Tripoli": "트리폴리",
    "Vaduz": "파두츠",
    "Vilnius": "빌뉴스",
    "Luxembourg": "룩셈부르크",
    "Antananarivo": "안타나나리보",
    "Lilongwe": "릴롱궤",
    "Kuala Lumpur": "쿠알라룸푸르",
    "Malé": "말레",
    "Bamako": "바마코",
    "Valletta": "발레타",
    "Majuro": "마주로",
    "Nouakchott": "누악쇼트",
    "Port Louis": "포트루이스",
    "Mexico City": "멕시코시티",
    "Palikir": "팔리키르",
    "Chisinau": "키시너우",
    "Monaco": "모나코",
    "Ulaanbaatar": "울란바토르",
    "Ulan Bator": "울란바토르",
    "Podgorica": "포드고리카",
    "Rabat": "라바트",
    "Maputo": "마푸투",
    "Naypyidaw": "네피도",
    "Windhoek": "빈트후크",
    "Yaren": "야렌",
    "Kathmandu": "카트만두",
    "Amsterdam": "암스테르담",
    "Wellington": "웰링턴",
    "Managua": "마나과",
    "Niamey": "니아메",
    "Abuja": "아부자",
    "Skopje": "스코페",
    "Oslo": "오슬로",
    "Muscat": "무스카트",
    "Islamabad": "이슬라마바드",
    "Ngerulmud": "응게룰무드",
    "Panama City": "파나마시티",
    "Port Moresby": "포트모르즈비",
    "Asunción": "아순시온",
    "Lima": "리마",
    "Manila": "마닐라",
    "Warsaw": "바르샤바",
    "Lisbon": "리스본",
    "Doha": "도하",
    "Bucharest": "부쿠레슈티",
    "Moscow": "모스크바",
    "Kigali": "키갈리",
    "Basseterre": "바스테르",
    "Castries": "캐스트리스",
    "Kingstown": "킹스타운",
    "Apia": "아피아",
    "San Marino": "산마리노",
    "São Tomé": "상투메",
    "Riyadh": "리야드",
    "Dakar": "다카르",
    "Belgrade": "베오그라드",
    "Victoria": "빅토리아",
    "Freetown": "프리타운",
    "Singapore": "싱가포르",
    "Bratislava": "브라티슬라바",
    "Ljubljana": "류블랴나",
    "Honiara": "호니아라",
    "Mogadishu": "모가디슈",
    "Pretoria": "프리토리아",
    "Juba": "주바",
    "Madrid": "마드리드",
    "Sri Jayawardenepura Kotte": "스리자야와르데네푸라코테",
    "Khartoum": "하르툼",
    "Paramaribo": "파라마리보",
    "Stockholm": "스톡홀름",
    "Bern": "베른",
    "Damascus": "다마스쿠스",
    "Taipei": "타이베이",
    "Dushanbe": "두샨베",
    "Dodoma": "도도마",
    "Bangkok": "방콕",
    "Lomé": "로메",
    "Nukuʻalofa": "누쿠알로파",
    "Port of Spain": "포트오브스페인",
    "Tunis": "튀니스",
    "Ankara": "앙카라",
    "Ashgabat": "아시가바트",
    "Funafuti": "푸나푸티",
    "Kampala": "캄팔라",
    "Kyiv": "키이우",
    "Abu Dhabi": "아부다비",
    "London": "런던",
    "Washington, D.C.": "워싱턴 D.C.",
    "Montevideo": "몬테비데오",
    "Tashkent": "타슈켄트",
    "Port Vila": "포트빌라",
    "Vatican City": "바티칸시티",
    "Caracas": "카라카스",
    "Hanoi": "하노이",
    "Sana'a": "사나",
    "Harare": "하라레",
    "Washington DC": "워싱턴 디씨",
    "Macau": "마카오",
    "Hong Kong": "홍콩",
    "Hamilton": "해밀턴",
    "Oranjestad": "오라녜스타트",
    "Gibraltar": "지브롤터",
    "San Juan": "산후안",
    "George Town": "조지타운",
    "Nuuk": "누크",
    "Willemstad": "빌렘스타트",
    "Papeetē": "파페에테",
    "Papeete": "파페에테",
    "Charlotte Amalie": "샬럿아말리에",
    "El Aaiún": "엘아이운",
    "Bogotá": "보고타",
    "Asunción": "아순시온",
    "Lomé": "로메",
    "Malé": "말레",
    "São Tomé": "상투메",
    "West Island": "웨스트아일랜드",
    "Avarua": "아바루아",
    "Flying Fish Cove": "플라잉피시코브",
    "Stanley": "스탠리",
    "Tórshavn": "토르스하운",
    "St. Peter Port": "세인트피터포트",
    "Basse-Terre": "바스테르",
    "Cayenne": "카옌",
    "Hagåtña": "하갓냐",
    "City of Victoria": "빅토리아",
    "Douglas": "더글러스",
    "Diego Garcia": "디에고가르시아",
    "Saint Helier": "세인트헬리어",
    "South Tarawa": "사우스타라와",
    "Colombo": "콜롬보",
    "Marigot": "마리고",
    "Chișinău": "키시너우",
    "Saipan": "사이판",
    "Plymouth": "플리머스",
    "Fort-de-France": "포르드프랑스",
    "Mamoudzou": "마무주",
    "Nouméa": "누메아",
    "Alofi": "알로피",
    "Adamstown": "애덤스타운",
    "Ramallah": "라말라",
    "Saint-Denis": "생드니",
    "King Edward Point": "킹에드워드포인트",
    "Longyearbyen": "롱이어비엔",
    "City of San Marino": "산마리노",
    "Saint-Pierre": "생피에르",
    "Lobamba": "로밤바",
    "Philipsburg": "필립스뷔르흐",
    "Cockburn Town": "코번타운",
    "Fakaofo": "파카오포",
    "Nuku'alofa": "누쿠알로파",
    "Washington D.C.": "워싱턴 D.C.",
    "Road Town": "로드타운",
    "Mata-Utu": "마타우투",
    "Lusaka": "루사카"
};
